# -*- coding: utf-8 -*-
"""DsAssignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DDeoNXrcbMPdq3Dd_Lq4YetMUGVpHL_5

1.  Importing the required Library
"""

from itertools import groupby
import re

"""2. Getting the inputs and storing"""

S = input('S = ')
words = input('words = ').split(',')

"""3. Defining functions to check the streachy words"""

def extendedWords( s, words):
    def groupWord(st:str):
            groups = groupby(st)
            result = [(label, sum(1 for _ in group)) for label, group in groups]
            return result

    sGroup=groupWord(s)
    cnt=0
    for word in words:
        temp=groupWord(word)
        if len(temp)!=len(sGroup):
           cnt=cnt
        else :
           flag = True
           for i in range (len(temp)):
             if (sGroup[i][0]==temp[i][0]) :
               if(temp[i][1]==sGroup[i][1]) :
                  flag=flag
               elif(temp[i][1]>sGroup[i][1]):
                  flag=False
               elif(sGroup[i][1]<3) :
                  flag=False
               else:
                  False
           if flag:
              cnt+=1
    return cnt

"""4. Checking the constraints using regex and printing Output

"""

if(len(S)>=0 and len(S)<=100 and len(words)>=0 and len(words)<=100) :
  exp = re.compile("[a-z]{2,}")
  if(re.findall(exp,S)):
    t=1
    for i in range (len(words)):
        if(len(words[i])>=0 and len(words[i])<=100):
          if(re.findall(exp,words[i])):
            t=t
          else:
            t=0
            print("The word is not purely lower case")
        else:
          t=0
          print("The length of words is beyond 100 words")
    if(t):
      output=extendedWords(S, words)
      print("Output: ",output)
  else:
    print("The string S is not purly case")
else:
  print("The length of the string is beyond 100 words")